_album:
    pattern:  /album
    defaults: { _controller: DemoTutorialBundle:Default:index }

_album_add:
    pattern:  /album/add
    defaults: { _controller: DemoTutorialBundle:Default:add }

_album_add_save:
    pattern:  /album/add/save
    defaults: { _controller: DemoTutorialBundle:Default:add_save }

_album_edit:
    pattern:  /album/edit/{id}
    defaults: { _controller: DemoTutorialBundle:Default:edit }
    requirements:
        id: '[0-9]+'

_album_edit_save:
    pattern:  /album/edit/save
    defaults: { _controller: DemoTutorialBundle:Default:edit_save }

_album_delete:
    pattern:  /album/delete/{id}
    defaults: { _controller: DemoTutorialBundle:Default:delete }
    requirements:
        id: '[0-9]+'

_album_delete_save:
    pattern:  /album/delete/save
    defaults: { _controller: DemoTutorialBundle:Default:delete_save }

_create_test:
    pattern:   /create_test
    defaults: { _controller: DemoTutorialBundle:Default:create }
